chore(deps): update consensys/teku docker tag to v26.3.0 (#435)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [consensys/teku](https://docs.teku.consensys.io/)
([source](https://redirect.github.com/Consensys/teku)) | minor |
`26.2.0` → `26.3.0` |

---

### Release Notes

<details>
<summary>Consensys/teku (consensys/teku)</summary>

###
[`v26.3.0`](https://redirect.github.com/Consensys/teku/releases/tag/26.3.0)

[Compare
Source](https://redirect.github.com/Consensys/teku/compare/26.2.0...26.3.0)

This is a mandatory update containing the fix for recent mainnet beacon
state serialization issue as well as performance improvements and
library updates.

The mainnet issue is showing in logs as the following error:

```
2026-03-05 16:16:26.201 ERROR - Storage update failed, retrying.
java.util.concurrent.CompletionException: java.lang.NegativeArraySizeException: -215782466
at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
at tech.pegasys.teku.storage.server.RetryingStorageUpdateChannel.retry(RetryingStorageUpdateChannel.java:133)
at tech.pegasys.teku.storage.server.RetryingStorageUpdateChannel.onStorageUpdate(RetryingStorageUpdateChannel.java:86)
at tech.pegasys.teku.storage.server.CombinedStorageChannelSplitter.onStorageUpdate(CombinedStorageChannelSplitter.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
...
```

##### Downloads

- Available as `26.3.0` on
[Dockerhub](https://hub.docker.com/r/consensys/teku)
- Download the binary distribution:
-
[tar.gz](https://artifacts.consensys.net/public/teku/raw/names/teku.tar.gz/versions/26.3.0/teku-26.3.0.tar.gz)
(sha256:
`2852f622bcc5064d6e2da5bc2cd852477fa9ca179ab565d3303043c26bfbc0ae`)
-
[zip](https://artifacts.consensys.net/public/teku/raw/names/teku.zip/versions/26.3.0/teku-26.3.0.zip)
(sha256:
`c34c8e39c5efc33cb7cb9cb0e1f8ffdcb57aee6c1cde4fc80a995b68da233978`)

##### Additions and Improvements

- Use jemalloc in our docker images to improve memory allocation
- Nodes with >50% custody requirements will be able to import blocks
after downloading 50% of the sidecars, and the remaining sidecars will
be handled as a background task. This includes nodes servicing
validators in excess of 2048 eth effective balance, as well as voluntary
supernodes.

##### Bug Fixes

- fixed SSZ serialization bug causing an integer overflow while
calculating ssz size.
- fixed an issue with dependent root calculation which was causing
future epoch block proposal duties to be recalculated.
- fixed v1 proposer duties returning incompatible roots for the v1
endpoint (should be compatible with pre-fulu dependent roots).

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/ObolNetwork/charon-distributed-validator-node).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0My41Ni4wIiwidXBkYXRlZEluVmVyIjoiNDMuNTYuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOlsicmVub3ZhdGUvZG9ja2VyIl19-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>